# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70443a8e4c2cd5c9abc8ec919754bcd005fe1f220320177162841016eb3942c3c4c7311ca718254e26836949cce9c884e27f686cdce3df6aca32451f15c02b04

test:
  secret_key_base: d624c7acc303819075e4f0c639c35ed51b46141417a15c9186a0047075e2f9b4696006b1704b31a7eff08fa5e7971e919364304ead46c893c07e48d5c1e30e98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
